version: "3.4"
   
services:
  db:
    image: postgres:13
    container_name: postgres_vstore
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      #- ./sql_scripts:/docker-entrypoint-initdb.d/
      - postgres_vstore_db:/var/lib/postgresql/data
      
volumes:
  postgres_vstore_db: