version: "3.4"

services: 
  rabbitmq_local:
    image: rabbitmq:3.8-management
    container_name: rabbitmq_vstore
    environment:
        RABBITMQ_ERLANG_COOKIE: "A6A7A874AA69329372AA75353314A7"
        RABBITMQ_DEFAULT_USER: "admin"
        RABBITMQ_DEFAULT_PASS: "admin"
        RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    labels:
        NAME: "rabbitmq_vstore"
    volumes:
       - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
       - rabbitmq_vstore_volume:/var/lib/rabbitmq:rw

volumes:
  rabbitmq_vstore_volume: